language: cpp
compiler: clang

matrix:
  include:
    - os: linux
      sudo: false
      dist: xenial
      compiler: clang-10

    - os: osx
      osx_image: xcode10.1
      compiler: clang

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - sourceline: 'deb https://apt.llvm.org/xenial/ llvm-toolchain-xenial-10 main'
        key_url: 'https://apt.llvm.org/llvm-snapshot.gpg.key'
    packages:
      - cmake
      - clang-10 libc++-10-dev libc++abi-10-dev

script:
  - mkdir build
  - cd build
  - cmake ..
  - make
  - cd ../artifacts
  - ./yukcorlib_test

# Disable notifications
notifications:
  email: false